# Site settings
title: BlissForge
description: BlissForge
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. https://example.com

# User settings
username: BlissForge
user_description: BlissForge is a home-based indie game studio focused on the arcade genre. Founded in 2012 by the sole proprietor Lorenzo Pappalettera, a high school graduate game-developer who specializes in AI development and has lots of expertise in code architecture. We use well-known building blocks as well as our own. Most things are being made in-house from scratch. We strive to create games with the same level of quality as AAA games. If you can dream it, we can make it! Games that will enrich your soul, that is our mission. We are always on the search for something profound.
user_title: Live in your world, play in ours!
#email: lorenzo.pappalettera@gmail.com
#twitter_username: BlissForge7
#github_username:  BlissForge
#..SKIP

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
